# This file determines the jobs that we run in this branch on Jenkins.
# Default architecture is x86_64
jobs:
# YB_TODO: tests fail with "stack depth limit exceeded"
#  - os: alma8
#    compiler: clang16
#    build_type: asan
#    release_artifact: false

# YB_TODO: build failure:
# libpq.so.5.15:                 U __tsan_func_exit
# libpq must not be calling any function which invokes exit
#  - os: centos7
#    compiler: clang17
#    build_type: tsan
#    release_artifact: false

  - os: centos7
    compiler: clang17
    build_type: debug
    release_artifact: false

# YB_TODO: build failure "ld.lld: error: duplicate symbol: fsync_fname"
#  - os: centos7
#    compiler: clang16
#    build_type: release
#    build_opts: YB_LINKING_TYPE=full-lto
#    release_artifact: true
#
#  - os: alma8
#    compiler: clang16
#    build_type: release
#    architecture: aarch64
#    release_artifact: true

  - os: alma8
    compiler: clang16
    build_type: debug
    architecture: aarch64
    release_artifact: false

  - os: alma8
    compiler: gcc11
    build_type: fastdebug
    release_artifact: false

  - os: mac12
    compiler: clang
    build_type: release
    architecture: arm64
    release_artifact: true

  - os: mac12
    compiler: clang
    build_type: release
    architecture: x86_64
    release_artifact: true

  - os: ubuntu20.04
    compiler: clang16
    build_type: debug
    release_artifact: false
