---
# Error: Yugabyte.MergeConflictMarkers
#
# Checks for the presence of merge conflict markers.
#
# For a list of all options, see https://errata-ai.gitbook.io/vale/getting-started/styles
#
# Borrowed from GitLab's vale styles:
# https://gitlab.com/gitlab-org/gitlab/-/tree/master/doc/.vale/gitlab

extends: existence
message: 'Merge conflict marker "%s" found.'
#link: https://docs.gitlab.com/ee/development/code_review.html#merging-a-merge-request
level: error
scope: raw
raw:
  - '\n<<<<<<< .+\n|\n=======\n|\n>>>>>>> .+\n'
