---
# Error: Yugabyte.Substitutions
#
# Checks for misused terms that should never be used at Yugabyte.
# SubstitutionWarning.yml and SubstitionSuggestions.yml also exist.
#
# For a list of all options, see https://docs.errata.ai/vale/styles
extends: substitution
message: 'Use "%s" instead of "%s".'
level: error
ignorecase: true
swap:
  styleguide: style guide
  yaml: YAML
#  to login: to log in
#  can login: can log in
#  to log-in: to log in
#  can log-in: can log in
#  to signin: to sign in
#  can signin: can sign in
#  to sign-in: to sign in
#  can sign-in: can sign in
#  x509: X.509
#  developer access: the Developer role
#  developer permission: the Developer role
#  developer permissions: the Developer role
#  maintainer access: the Maintainer role
#  maintainer permission: the Maintainer role
#  maintainer permissions: the Maintainer role
#  owner access: the Owner role
#  owner permission: the Owner role
#  owner permissions: the Owner role
