# Copyright 2020 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Test ansible remote command - ls
  shell: ls

- name: Create sudo password file in tmp directory
  copy:
    dest: "{{ remote_tmp_dir | default('/tmp') ~ '/.yb_sudo_pass.sh' }}"
    content: "export YB_SUDO_PASS={{ ansible_become_pass }}"
  when: ansible_become_pass is defined and yb_sudo_pass_file is not defined

- name: Create sudo password file at yb_sudo_pass_file
  copy:
    dest: "{{ yb_sudo_pass_file }}"
    content: "export YB_SUDO_PASS={{ ansible_become_pass }}"
  when: ansible_become_pass is defined and yb_sudo_pass_file is defined
